### ISSUE TITLE
Счет над полями не отображается

### ISSUE THREAD

**Issue by te5in** [diduk001/battleship#10]
<img width="1206" alt="Снимок экрана 2022-01-06 в 14 46 17" src="https://user-images.githubusercontent.com/11004474/148363491-62cbf3b4-562d-431c-80cf-a42bf987b942.png">

**Comment by diduk001** [comment]
Fixed with `3beb905963105c7c36f0829bb414ad791dae4580` and `1f6f27370c4ac9ee4c66053b1763d626bb7e77fe` . Included local Roboto font from [here](https://fonts.google.com/share?selection.family=Roboto).
